// Shared generation helpers for manifest-backed OpenClaw plugin tools.
// 本文件提供面向 OpenClaw 静态 manifest 工具声明的共享生成辅助能力。

import { readFile, writeFile } from "node:fs/promises";
import type { JsonObject, VulcanToolDescriptor } from "./types.js";

// GeneratedModuleRenderParams describes the TypeScript module generated from host descriptors.
// GeneratedModuleRenderParams 描述由宿主 descriptor 生成 TypeScript 模块所需的参数。
export interface GeneratedModuleRenderParams {
  exportName: string;
  descriptors: VulcanToolDescriptor[];
}

// UpdateManifestToolsParams describes a manifest contracts.tools synchronization request.
// UpdateManifestToolsParams 描述一次 manifest contracts.tools 同步请求。
export interface UpdateManifestToolsParams {
  manifestPath: string;
  baseToolNames: string[];
  generatedToolNames: string[];
}

// GENERATED_FILE_HEADER is emitted into generated TypeScript modules to prevent manual edits.
// GENERATED_FILE_HEADER 会写入生成的 TypeScript 模块，用于提示不要手工修改。
const GENERATED_FILE_HEADER = [
  "// This file is generated by Vulcan OpenClaw plugin sync scripts. Do not edit manually.",
  "// 本文件由 Vulcan OpenClaw 插件同步脚本生成，请勿手工修改。",
  "",
].join("\n");

// normalizeGeneratedDescriptor trims descriptor fields and drops invalid tool records.
// normalizeGeneratedDescriptor 清洗 descriptor 字段，并丢弃非法工具记录。
export function normalizeGeneratedDescriptor(
  descriptor: VulcanToolDescriptor,
): VulcanToolDescriptor | null {
  const name = descriptor.name.trim();
  if (!name) {
    return null;
  }
  const normalized = {
    name,
    description: descriptor.description.trim(),
    inputSchema: normalizeJsonObject(descriptor.inputSchema),
    ...(descriptor.annotations ? { annotations: normalizeJsonObject(descriptor.annotations) } : {}),
    ...(descriptor.skillId ? { skillId: descriptor.skillId } : {}),
    ...(descriptor.entryName ? { entryName: descriptor.entryName } : {}),
    ...(descriptor.rootName ? { rootName: descriptor.rootName } : {}),
    ...(descriptor.skillDir ? { skillDir: descriptor.skillDir } : {}),
    ...(descriptor.source ? { source: descriptor.source } : {}),
  } satisfies VulcanToolDescriptor;
  return normalized;
}

// normalizeGeneratedDescriptors deduplicates descriptors by exact OpenClaw tool name.
// normalizeGeneratedDescriptors 按 OpenClaw 工具名精确去重 descriptor。
export function normalizeGeneratedDescriptors(
  descriptors: VulcanToolDescriptor[],
): VulcanToolDescriptor[] {
  const seen = new Set<string>();
  const normalized: VulcanToolDescriptor[] = [];
  for (const descriptor of descriptors) {
    const entry = normalizeGeneratedDescriptor(descriptor);
    if (!entry || seen.has(entry.name)) {
      continue;
    }
    seen.add(entry.name);
    normalized.push(entry);
  }
  return normalized.toSorted((left, right) => left.name.localeCompare(right.name));
}

// renderGeneratedDescriptorModule renders descriptors as an importable TypeScript module.
// renderGeneratedDescriptorModule 将 descriptor 渲染为可直接 import 的 TypeScript 模块。
export function renderGeneratedDescriptorModule(params: GeneratedModuleRenderParams): string {
  const descriptors = normalizeGeneratedDescriptors(params.descriptors);

  // Use JSON serialization for generated data so descriptors stay data-only and reviewable.
  // 使用 JSON 序列化生成数据，确保 descriptor 保持纯数据且便于审核。
  return [
    GENERATED_FILE_HEADER,
    'import type { VulcanToolDescriptor } from "@vulcan-plugins-openclaw/shared";',
    "",
    `// ${params.exportName} contains host-synchronized tool descriptors used by OpenClaw runtime registration.`,
    `// ${params.exportName} 包含宿主同步的工具描述，用于 OpenClaw 运行时注册。`,
    `export const ${params.exportName}: VulcanToolDescriptor[] = ${stableStringify(descriptors, 2)};`,
    "",
  ].join("\n");
}

// updateManifestTools rewrites openclaw.plugin.json contracts.tools from generated descriptors.
// updateManifestTools 根据生成 descriptor 重写 openclaw.plugin.json 的 contracts.tools。
export async function updateManifestTools(params: UpdateManifestToolsParams): Promise<string[]> {
  const manifest = await readJsonRecord(params.manifestPath);
  const contracts = readRecord(manifest.contracts);
  const tools = uniqueNonEmptyStrings([...params.baseToolNames, ...params.generatedToolNames]);

  // OpenClaw validates runtime registrations against contracts.tools, so this must be exact.
  // OpenClaw 会用 contracts.tools 校验运行时注册，因此这里必须保持精确。
  manifest.contracts = {
    ...contracts,
    tools,
  };
  await writeFile(params.manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
  return tools;
}

// writeTextFile writes generated text with a trailing newline normalized by callers.
// writeTextFile 写入生成文本，尾部换行由调用方统一处理。
export async function writeTextFile(filePath: string, content: string): Promise<void> {
  await writeFile(filePath, content, "utf8");
}

// uniqueNonEmptyStrings keeps first occurrence order while dropping blank strings.
// uniqueNonEmptyStrings 保留首次出现顺序并丢弃空字符串。
export function uniqueNonEmptyStrings(values: readonly string[]): string[] {
  const seen = new Set<string>();
  const result: string[] = [];
  for (const value of values) {
    const normalized = value.trim();
    if (!normalized || seen.has(normalized)) {
      continue;
    }
    seen.add(normalized);
    result.push(normalized);
  }
  return result;
}

// normalizeJsonObject ensures generated schemas always remain JSON objects.
// normalizeJsonObject 确保生成的 schema 始终保持 JSON 对象。
function normalizeJsonObject(value: JsonObject | undefined): JsonObject {
  return value && typeof value === "object" && !Array.isArray(value) ? value : {};
}

// readJsonRecord loads a JSON file and validates that the root is an object.
// readJsonRecord 加载 JSON 文件并校验根节点为对象。
async function readJsonRecord(filePath: string): Promise<Record<string, unknown>> {
  const parsed = JSON.parse(await readFile(filePath, "utf8")) as unknown;
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error(`JSON root must be an object: ${filePath}`);
  }
  return parsed as Record<string, unknown>;
}

// readRecord narrows loose JSON fields into mutable object records.
// readRecord 将松散 JSON 字段收窄为可变对象 record。
function readRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : {};
}

// stableStringify serializes generated data with sorted object keys for reviewable diffs.
// stableStringify 使用排序后的对象键序列化生成数据，便于审查 diff。
function stableStringify(value: unknown, spaces: number): string {
  return JSON.stringify(sortJsonValue(value), null, spaces);
}

// sortJsonValue recursively sorts plain object keys while preserving arrays.
// sortJsonValue 递归排序普通对象键，同时保持数组顺序。
function sortJsonValue(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map((entry) => sortJsonValue(entry));
  }
  if (!value || typeof value !== "object") {
    return value;
  }
  const record = value as Record<string, unknown>;
  const sorted: Record<string, unknown> = {};
  for (const key of Object.keys(record).toSorted((left, right) => left.localeCompare(right))) {
    sorted[key] = sortJsonValue(record[key]);
  }
  return sorted;
}
